/**
 * The worker the dev server hands out — it registers, claims, and caches **nothing**.
 *
 * ⚠️ **Without one, development and production disagree about whether a worker exists at all.** A
 * product that calls `registerStationWorker()` unconditionally gets a 404 and a console error every
 * time it is run locally, which teaches everybody to ignore the one message that would tell them the
 * scope is wrong. And a *caching* worker in development is worse still: it serves yesterday's module
 * back over a live edit, which reads as the dev server being broken.
 *
 * So it is real enough to register and assert a scope against, and empty enough to be invisible.
 */
export function buildDevelopmentWorkerSource(): string {
  return `/*
 * Generated by @jmouse/pwa for the dev server. It caches nothing, on purpose.
 */
self.addEventListener("install", () => self.skipWaiting())
self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()))
`
}

export interface WorkerSourceOptions {
  /** Bumped by the build's own asset hashes, so a new build is a new cache rather than a merged one. */
  cacheName: string
  /** The hashed build output — everything safe to keep forever, because its name changes when it does. */
  precache: readonly string[]
  /** Addresses the worker must never answer from a cache — the API, and anything a product adds. */
  networkOnlyPrefixes: readonly string[]
  /**
   * Where the bundler writes its **content-hashed** output. Only what lives here may be answered
   * cache-first: its name changes when its bytes do, so a cached copy can never be the wrong one.
   */
  hashedAssetPrefix: string
}

/**
 * The service worker, as source, with this build's asset list already in it.
 *
 * ⚠️ **Generated rather than shipped as a module, and that is not a shortcut.** A worker is fetched by
 * the browser as its own top-level script, so it cannot be an import of the application bundle; and a
 * *module* worker is still refused by enough installed browsers that shipping one would make the
 * offline story depend on which phone somebody has. A classic script with the precache list baked in
 * has neither problem.
 *
 * ⚠️ **A service worker is the one thing here that can make a product permanently unupdatable**, in a
 * browser nobody can reach to fix it. Every rule below exists for that reason rather than for speed:
 *
 * - **The HTML entries are never precached and never served cache-first.** A stale entry is a station
 *   that can no longer discover a new manifest or a new bundle — the exact shape of "unupdatable".
 * - **`skipWaiting` is never called on its own.** The new worker waits until the page asks, so a
 *   worker cannot swap itself out from under a half-filled form.
 * - **Old caches are deleted on activate**, so a bad build's cache does not outlive the build.
 */
export function buildWorkerSource(options: WorkerSourceOptions): string {
  const { cacheName, precache, networkOnlyPrefixes, hashedAssetPrefix } = options

  return `/*
 * Generated by @jmouse/pwa. Do not edit — it is rewritten on every build.
 *
 * One worker for every station on this origin. Stations differ by manifest, never by scope, so this
 * is registered once at '/' and serves all of them.
 */
const CACHE_NAME = ${JSON.stringify(cacheName)}
const PRECACHE = ${JSON.stringify(precache, null, 2)}
const NETWORK_ONLY_PREFIXES = ${JSON.stringify(networkOnlyPrefixes, null, 2)}
const HASHED_ASSET_PREFIX = ${JSON.stringify(hashedAssetPrefix)}

self.addEventListener("install", (event) => {
  // No skipWaiting here. The new worker waits until a page asks for it, so nobody loses a form they
  // were filling in because a deploy landed.
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener("message", (event) => {
  // The ONLY way this worker ever takes over early, and the page is what asks.
  if (event.data && event.data.type === "JMOUSE_PWA_APPLY_UPDATE") {
    self.skipWaiting()
  }
})

function isNetworkOnly(url) {
  return NETWORK_ONLY_PREFIXES.some((prefix) => url.pathname.startsWith(prefix))
}

self.addEventListener("fetch", (event) => {
  const request = event.request

  if (request.method !== "GET") {
    return
  }

  const url = new URL(request.url)

  if (url.origin !== self.location.origin || isNetworkOnly(url)) {
    return
  }

  // ⚠️ A navigation is answered from the network first, ALWAYS. The cached copy is a last resort for
  // a reader who is offline — never the normal answer — because a cached document is a document that
  // can no longer discover a new manifest or a new bundle.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          // Kept only so there is SOMETHING to answer with offline. It is never preferred while the
          // network is reachable, so it can never be the stale copy that hides a new build.
          if (response.ok && response.type === "basic") {
            const copy = response.clone()

            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy))
          }

          return response
        })
        .catch(() => caches.match(request).then((cached) => cached || Response.error())),
    )

    return
  }

  function remember(response) {
    if (response.ok && response.type === "basic") {
      const copy = response.clone()

      caches.open(CACHE_NAME).then((cache) => cache.put(request, copy))
    }

    return response
  }

  // ⚠️ Cache-first is allowed for HASHED output only. Its name changes when its bytes do, so a cached
  // copy can never be the wrong one.
  if (url.pathname.startsWith(HASHED_ASSET_PREFIX)) {
    event.respondWith(caches.match(request).then((cached) => cached || fetch(request).then(remember)))

    return
  }

  // ⚠️ Everything else is UNHASHED — a manifest, an icon, a font copied verbatim out of the public
  // directory. Answering those cache-first would pin the first copy forever, because a new build gives
  // them the same name. Stale-while-revalidate serves instantly, then repairs itself within one load.
  event.respondWith(
    caches.match(request).then((cached) => {
      const fresh = fetch(request)
        .then(remember)
        .catch(() => cached || Response.error())

      return cached || fresh
    }),
  )
})
`
}
